Assignment Day 3 | 11th November 2020

Question 1

Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
import numpy as np
arr = np.arange(2,51,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


Questions 2

Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [6]:
import numpy as np
arr1=[] 
arr2=[]
for i in range(0, 5): 
    e = int(input())
    arr1.append(e)
for i in range(0, 5): 
    e = int(input())
    arr2.append(e) 
arr1 = np.array(arr1)
arr2 = np.array(arr2)
print(np.concatenate((arr1,arr2)))
print(np.sort(np.concatenate((arr1,arr2))))

9
8
7
6
5
4
3
2
1
10
[ 9  8  7  6  5  4  3  2  1 10]
[ 1  2  3  4  5  6  7  8  9 10]


Questions 3:

Write a code snippet to find the dimensions of a ndarray and its size.

In [9]:
import numpy as np
arr = np.array([[2,3],[1,3],[1,4],[9,6]])
print(arr.ndim)
print(arr.size)

2
8


Questions 4:

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [17]:
import numpy as np
arr=np.random.rand(10,)
print(arr.shape)
print(arr.ndim,"D array")
twod_arr = arr[np.newaxis, :]
print(twod_arr.shape)
print(twod_arr.ndim,"D array")

(10,)
1 D array
(1, 10)
2 D array


Questions 5:

Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()


In [20]:
import numpy as np
arr1=np.random.rand(2,2)
arr2=np.random.rand(2,2)
print("Vertical Stack") 
print(np.vstack((arr1,arr2)))
print("Horizontal Stack") 
print(np.hstack((arr1,arr2)))

Vertical Stack
[[0.05248855 0.66902095]
 [0.79031943 0.46385571]
 [0.02276637 0.47607352]
 [0.32397049 0.15276483]]
Horizontal Stack
[[0.05248855 0.66902095 0.02276637 0.47607352]
 [0.79031943 0.46385571 0.32397049 0.15276483]]


Questions 6:

How to get unique items and counts of unique items?

In [24]:
import numpy as np
arr = np.array([11,22,33,44,55,66,77,11,44,44,55,66,88,77,77,77,77])
print(np.unique(arr,return_counts=True))

(array([11, 22, 33, 44, 55, 66, 77, 88]), array([2, 1, 1, 3, 2, 2, 5, 1]))
